ENTITY_PROCESS_TEMPLATE = "process_template"
ENTITY_TENANT_PROCESS_CONFIGURATION = "tenant_process_configuration"
ENTITY_PROCESS_DEFINITION_VERSION = "process_definition_version"
ENTITY_PROCESS_RUN = "process_run"

EVENT_PROCESS_TRANSITION_APPLIED = "process_transition.applied"

MAX_TRANSITIONS = 100
MAX_STAGE_CODES = 50
MAX_PUBLISH_REASON_LENGTH = 2000
POLICY_SCHEMA_VERSION = 1
