ENTITY_PROCESS_TEMPLATE = "process_template"
ENTITY_TENANT_PROCESS_CONFIGURATION = "tenant_process_configuration"
ENTITY_PROCESS_DEFINITION_VERSION = "process_definition_version"

MAX_TRANSITIONS = 100
MAX_STAGE_CODES = 50
MAX_PUBLISH_REASON_LENGTH = 2000
POLICY_SCHEMA_VERSION = 1
